# Generated by Django 3.1.7 on 2021-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='c_id',
            field=models.CharField(default='NON', max_length=4, verbose_name='Course_ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_name',
            field=models.CharField(default='', max_length=20, verbose_name='Course_name'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_photo',
            field=models.ImageField(default='', upload_to='Courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='coursess', to='main_page.StudentProfile'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main_page.TeacherProfile'),
        ),
    ]
