# Generated by Django 3.1.7 on 2021-06-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizvariants',
            name='quiz_name',
        ),
        migrations.DeleteModel(
            name='QuizName',
        ),
        migrations.DeleteModel(
            name='QuizVariants',
        ),
    ]
