# Generated by Django 3.1.7 on 2022-05-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpaidamount',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentpaidamount',
            name='paidAmount',
        ),
        migrations.RemoveField(
            model_name='studentpaidamount',
            name='paidDate',
        ),
        migrations.RemoveField(
            model_name='studentpaidamount',
            name='student',
        ),
    ]
