# Generated by Django 3.1.7 on 2021-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20211030_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=50)),
                ('description_header', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('subscription_header', models.CharField(max_length=50)),
                ('subscription_text', models.CharField(max_length=100)),
                ('our_specialities_header', models.CharField(max_length=50)),
                ('our_specialities', models.TextField()),
                ('exam_dates_1', models.ImageField(blank=True, upload_to='exam_pics/')),
                ('exam_dates_2', models.ImageField(blank=True, upload_to='exam_pics/')),
                ('summativ_note', models.TextField()),
                ('exam_details', models.TextField()),
            ],
        ),
    ]
