# Generated by Django 3.1.7 on 2021-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_frontpagedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontpagedata',
            old_name='our_specialities',
            new_name='our_specialities_1',
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='subscription_form_header',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
