# Generated by Django 3.1.7 on 2022-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_delete_studentpaidamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
