# Generated by Django 3.1.7 on 2022-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
