# Generated by Django 3.1.7 on 2021-12-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20211201_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagedata',
            name='announcement',
            field=models.ImageField(blank=True, upload_to='exam_pics/'),
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_2_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_3_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_4_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frontpagedata',
            name='our_specialities_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frontpagedata',
            name='our_specialities_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frontpagedata',
            name='our_specialities_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frontpagedata',
            name='our_specialities_4',
            field=models.CharField(max_length=50),
        ),
    ]
