# Generated by Django 3.1.7 on 2021-12-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20211201_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagedata',
            name='our_specialities_1_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
