# Generated by Django 3.1.7 on 2022-06-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_teacherprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdpaidamount',
            name='paidDate',
            field=models.DateField(),
        ),
    ]
