# Generated by Django 3.1.7 on 2021-08-25 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_result_quiz_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 12, 52, 54, 718816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='result',
            name='quiz_work_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 12, 52, 54, 718816, tzinfo=utc)),
        ),
    ]
