# Generated by Django 3.1.7 on 2021-12-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_frontpagedata_our_specialities_1_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='team_member/')),
                ('member_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
