# Generated by Django 3.1.7 on 2022-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20220617_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_id',
            field=models.CharField(default='NON', max_length=4, unique=True, verbose_name='Course_ID'),
        ),
    ]
