# Generated by Django 3.1.7 on 2021-08-26 18:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210825_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 18, 37, 56, 978030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='result',
            name='quiz_work_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
