# Generated by Django 3.1.7 on 2021-08-26 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20210826_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
