# Generated by Django 3.1.7 on 2022-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_stdpaidamount_qaime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdpaymentamount2',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stdpaidamount',
            name='qaime',
            field=models.FileField(default='/pdf/qaime.pdf', upload_to='pdf/'),
        ),
    ]
