# Generated by Django 3.1.7 on 2021-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20211204_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontMenuNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_exams', models.CharField(max_length=30)),
                ('about_us', models.CharField(max_length=30)),
                ('contacts', models.CharField(max_length=30)),
            ],
        ),
    ]
